# Generated by Django 6.0.1 on 2026-01-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('coeficiente', models.FloatField()),
                ('taxa', models.FloatField(default=1.85)),
                ('prazo', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('cms', models.FloatField()),
                ('tipo_cms', models.CharField(max_length=1)),
                ('digital', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.banco')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacao.operacao')),
            ],
            options={
                'verbose_name': 'Tabela',
                'verbose_name_plural': 'Tabelas',
            },
        ),
    ]
