# Generated by Django 6.0.1 on 2026-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='digital',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='taxa',
            field=models.FloatField(default=1.85),
        ),
    ]
