# Generated by Django 6.0.1 on 2026-01-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14)),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('iletrado', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(max_length=50)),
                ('orgao_emissor', models.CharField(max_length=20)),
                ('uf_emissao', models.CharField(max_length=2)),
                ('data_emissao', models.DateField()),
                ('naturalidade', models.CharField(max_length=50)),
                ('uf_naturalidade', models.CharField(max_length=2)),
                ('pai', models.CharField(max_length=50)),
                ('mae', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf_cidade', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
