# Generated by Django 6.0.1 on 2026-01-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
    ]
