# Generated by Django 6.0.1 on 2026-01-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('convenio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenio.matricula')),
            ],
            options={
                'verbose_name': 'Card de Ofertas',
                'verbose_name_plural': 'Cards de Ofertas',
            },
        ),
    ]
