# Generated by Django 6.0.1 on 2026-02-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoferta',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('DIGITACAO', 'Digitação Solicitada'), ('DIGITADO', 'Digitado'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=100),
        ),
    ]
