# Generated by Django 6.0.1 on 2026-01-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardoferta',
            name='propostas',
        ),
    ]
