# Generated by Django 6.0.1 on 2026-01-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0002_remove_cardoferta_propostas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardoferta',
            options={'verbose_name': 'Card de Ofertas', 'verbose_name_plural': 'Cards de Ofertas'},
        ),
    ]
