# Generated by Django 6.0.1 on 2026-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0003_cardoferta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoferta',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardoferta',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('DIGITACAO', 'Digitação Solicitada'), ('DIGITADO', 'Digitado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NAO_INICIADO', max_length=100),
        ),
    ]
