# Generated by Django 6.0.1 on 2026-02-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0004_cardoferta_is_blocked_alter_cardoferta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoferta',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cardoferta',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('DIGITACAO', 'Aguardando Digitação'), ('ANDAMENTO', 'Andamento'), ('FORMALIZACAO', 'Aguardando Formalização'), ('ATENCAO', 'Precisa de Atenção'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='NAO_INICIADO', max_length=100),
        ),
    ]
