# Generated by Django 6.0.1 on 2026-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0005_cardoferta_active_alter_cardoferta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoferta',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
