# Generated by Django 6.0.1 on 2026-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0006_alter_cardoferta_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoferta',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardoferta',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('DIGITACAO', 'Aguardando Digitação'), ('ANDAMENTO', 'Andamento'), ('FORMALIZACAO', 'Aguardando Formalização'), ('ATENCAO', 'Precisa de Atenção'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('EXCLUIDO', 'Excluído')], default='NAO_INICIADO', max_length=100),
        ),
    ]
