# Generated by Django 6.0.1 on 2026-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0007_cardoferta_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoferta',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
