# Generated by Django 6.0.1 on 2026-02-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocard',
            name='status',
        ),
    ]
