# Generated by Django 6.0.1 on 2026-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_historicoproposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoproposta',
            name='status',
        ),
        migrations.AddField(
            model_name='historicoproposta',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
