# Generated by Django 6.0.1 on 2026-01-22 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('tabela', '0002_alter_tabela_ativo_alter_tabela_digital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ade', models.CharField(max_length=100)),
                ('bloqueado', models.BooleanField(default=False)),
                ('codigo_interno', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('cms', models.FloatField(blank=True, null=True)),
                ('parcela', models.FloatField()),
                ('prazo', models.PositiveIntegerField()),
                ('financiado', models.FloatField(blank=True, null=True)),
                ('saldo_devedor', models.FloatField(blank=True, null=True)),
                ('troco', models.FloatField()),
                ('prazo_original', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_restante', models.PositiveIntegerField(blank=True, null=True)),
                ('contrato_portado', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_origem', models.CharField(blank=True, max_length=3, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabela.tabela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposta.status')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='propostas/')),
                ('tipo', models.CharField(blank=True, choices=[('Documento Identificação', 'Documento Identificação'), ('Contrato', 'Contrato'), ('Contracheque', 'Contracheque'), ('Outro', 'Outro')], max_length=100, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='proposta.proposta')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
