# Generated by Django 6.0.1 on 2026-01-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_oferta', '0002_remove_cardoferta_propostas'),
        ('proposta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='card_oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card_oferta.cardoferta'),
        ),
    ]
