# Generated by Django 6.0.1 on 2026-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0002_proposta_card_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='secondary', max_length=15),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='ade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
