# Generated by Django 6.0.1 on 2026-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0002_alter_proposta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='ade_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
