# Generated by Django 6.0.1 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0004_alter_proposta_tabela_alter_proposta_usuario'),
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='tabela.tabela'),
        ),
    ]
