# Generated by Django 6.0.1 on 2026-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0005_alter_proposta_tabela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(blank=True, default='Aberto', max_length=100, null=True),
        ),
    ]
